name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v

    - name: Install go-msi
      run: go get github.com/mat007/go-msi

    - name: Install wix
      run: choco install -y wixtoolset

    - name: Set path
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
      shell: bash

    - name: build msi
      run: go-msi make --msi cdrom-trusted-autorun.msi --arch amd64 --version $env:GITHUB_RUN_ID --src .\templates\ --out "$pwd\temp"
    
    - uses: actions/upload-artifact@v2
      with:
        name: windows binaries
        path: |
          cdrom-trusted-autorun.exe
          cdrom-trusted-autorun.msi

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v

    - uses: actions/upload-artifact@v2
      with:
        name: linux binaries
        path: cdrom-trusted-autorun

